# yaml-language-server: $schema=https://json.schemastore.org/pre-commit-config.json

minimum_pre_commit_version: 2.17.0
fail_fast: false
default_stages:
  - commit
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-private-key
      - id: no-commit-to-branch
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-json
      - id: check-xml
      - id: pretty-format-json
        args:
          - --autofix
          - --no-sort-keys
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.6
    hooks:
      - id: forbid-binary
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.14.2
    hooks:
      - id: check-jsonschema
        name: Validate GitHub Workflows
        files: ^\.github/workflows/.*\.yml
        types:
          - yaml
        args:
          - --schemafile
          - https://json.schemastore.org/github-workflow.json
      - id: check-jsonschema
        name: Validate DependaBot
        files: ^\.github/dependabot\.yml
        types:
          - yaml
        args:
          - --schemafile
          - https://json.schemastore.org/dependabot-2.0.json
      - id: check-jsonschema
        name: Validate Pre-commit
        files: .*\.pre-commit-config\.yaml
        types:
          - yaml
        args:
          - --schemafile
          - https://json.schemastore.org/pre-commit-config.json
      - id: check-jsonschema
        name: Validate Docker-Compose
        files: .*docker-compose\.yml
        types:
          - yaml
        args:
          - --schemafile
          - https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
      - id: check-jsonschema
        name: Validate Renovate
        files: ^\.github/renovate\.json
        types:
          - json
        args:
          - --schemafile
          - https://docs.renovatebot.com/renovate-schema.json
          - --disable-format
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.21.2
    hooks:
      - id: commitizen
        name: Lint commit message
        stages:
          - commit-msg
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.15.3
    hooks:
      - id: gitleaks
        name: Detect hardcoded secrets
  - repo: local
    hooks:
      - id: maven-spotless
        name: Maven Spotless apply
        entry: bash -c './mvnw -q spotless:apply'
        language: system
        types: [java]
